### ISSUE TITLE
Retrieve password for vPro/ISM devices for both methods, CIRA and TLS Enterprise Modes

### ISSUE THREAD

**Issue by ctmorris88** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#197]
**Describe the bug** 🪲
Today there is no way to determine the Digest password (Static or Randomized) of the platform after it is activated with OAMTCT using a profile.   Since the profiles do not hold the password you set (memory), it is important to have a way to LOCATE the current Digest admin password on the vPro/ISM Devices.

This would apply to not only CIRA devices but TLS Enterprise as well.

**To Reproduce** 🪜
N/A

**Expected behavior**
Have a field within OAMTCT to show the current Digest Admin password.

**Screenshots** 🖼️

**AMT Device (please complete the following information):** 🖥️
N/A

**Service Deployment (please complete the following information):** ⛈️
N/A

**Additional context**

**Comment by bwendlandt-intel** [comment]
Hi Corey, Just wanted to follow up on this after some more discussion from the team.  There is no plan to implement this change as we offer the Sample Web UI as only a basic reference implementation. 

As you said, in order to securely implement this, it would require a robust MFA/User Auth service to be built and integrated with the UI among other production-level security considerations and burdens we do not want to take on for just a reference UI.  Today, this is out of scope for our goals and future plans of the Sample Web UI.  Looking forward, our plan is to continue to maintain and enhance the Sample Web UI as an agnostic vehicle for people to get hands-on with testing the toolkits features (APIs) and see how Open AMT integration can be done to a UI framework like Angular.

Developers and adopters of the toolkit, like an ISV/MSP/etc, that have these existing systems (Auth/MFA/etc) in place can decide to provide password access (via direct calls to Vault or like service) as a feature for their customers.

Closing the issue, please reach out if you have other questions on this topic.  Thanks!
